#!/bin/bash
#
# convenience call to ask for host info via x204->cobbler
#
if [ $# -eq 0 ]
then
    echo "usage: $0 host"
    exit 1
fi
if echo "$1" | grep -q \\\. 
then
    testhost="$1"
else
    testhost="$1.adm.denic.de"
fi
ssh x204.adm.denic.de ssh x10734.adm.denic.de rzconfig.pl all host report --host "$testhost"
exit 0
